# Generated by Django 3.2.8 on 2021-10-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='negotiable',
        ),
    ]
