# Generated by Django 3.2.5 on 2021-07-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='files',
            field=models.FileField(upload_to='item_images'),
        ),
    ]
