# Generated by Django 4.0.2 on 2022-07-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_item_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_or_new',
            field=models.CharField(choices=[('not disclosed', 'not disclosed'), ('used', 'used item'), ('fairly used', 'fairly used'), ('new item', 'new item')], default='1', max_length=20),
        ),
    ]
