# Generated by Django 3.2.5 on 2021-07-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, default='test.jpg', upload_to='profile_pics'),
        ),
    ]
