# Generated by Django 3.2.5 on 2021-07-07 08:58

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210706_2104'),
        ('user', '0005_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
    ]
